# path: book/projects/agentkit/agentkit/__init__.py
"""agentkit: the bounded, event-sourced agent loop of Chapter 19, reused by Chapters 20-22, 38, and 39."""
from .budget import Budget, BudgetUsage, TerminationReason
from .dod import (
    AllOf, AnyOf, Check, DefinitionOfDone, DoDResult, Verdict, Verifier, all_of, any_of, citations_grounded,
    contains_all, has_artifact, json_schema, matches, non_empty, tool_was_called,
)
from .errors import (
    ErrorClass, ImpossibleTaskError, ToolError, ToolPermissionError, ToolValidationError, TransientToolError,
    classify_error,
)
from .events import (
    AnyEvent, BudgetUpdated, Event, FinalAnswer, GoalSet, ModelDecision, Note, Resumed, StepCompleted, Stopped,
    ToolCallApproved, ToolCallDenied, ToolCallRequested, ToolResult, action_key, event_from_dict, event_from_json,
    event_to_json,
)
from .observations import Truncated, truncate_observation
from .replay import (
    DecisionSignature, RecordedLLM, RecordedPolicy, RecordedToolResults, ReplayExhausted, ReplayReport, ReplayTool,
    decision_signatures, replay,
)
from .runtime import DEFAULT_SYSTEM_PROMPT, AgentRuntime, Approver, LoopConfig, RunResult
from .state import AgentState, AgentStatus, CallRecord, Observation, apply, derive_state
from .store import EventStore, InMemoryEventStore, JsonlEventStore
from .tools import (
    DefaultPolicy, FunctionTool, PolicyDecision, SideEffect, Tool, ToolContext, ToolOutput, ToolPolicy, adapt_tool,
    IdempotencyMode, coerce_side_effect, executor_tools, function_tool, normalize_output, validate_arguments,
)

__version__ = "0.1.0"
__all__ = [
    "AgentRuntime",
    "AgentState",
    "AgentStatus",
    "AllOf",
    "AnyEvent",
    "AnyOf",
    "Approver",
    "Budget",
    "BudgetUpdated",
    "BudgetUsage",
    "CallRecord",
    "Check",
    "DEFAULT_SYSTEM_PROMPT",
    "DecisionSignature",
    "DefaultPolicy",
    "DefinitionOfDone",
    "DoDResult",
    "ErrorClass",
    "Event",
    "EventStore",
    "FinalAnswer",
    "FunctionTool",
    "GoalSet",
    "ImpossibleTaskError",
    "InMemoryEventStore",
    "JsonlEventStore",
    "LoopConfig",
    "ModelDecision",
    "Note",
    "Observation",
    "PolicyDecision",
    "RecordedLLM",
    "RecordedPolicy",
    "RecordedToolResults",
    "ReplayExhausted",
    "ReplayReport",
    "ReplayTool",
    "Resumed",
    "RunResult",
    "SideEffect",
    "StepCompleted",
    "Stopped",
    "TerminationReason",
    "Tool",
    "ToolCallApproved",
    "ToolCallDenied",
    "ToolCallRequested",
    "ToolContext",
    "ToolError",
    "ToolOutput",
    "ToolPermissionError",
    "ToolPolicy",
    "ToolResult",
    "ToolValidationError",
    "TransientToolError",
    "Truncated",
    "Verdict",
    "Verifier",
    "action_key",
    "adapt_tool",
    "all_of",
    "any_of",
    "apply",
    "citations_grounded",
    "coerce_side_effect",
    "classify_error",
    "contains_all",
    "decision_signatures",
    "derive_state",
    "event_from_dict",
    "event_from_json",
    "event_to_json",
    "executor_tools",
    "IdempotencyMode",
    "function_tool",
    "has_artifact",
    "json_schema",
    "matches",
    "non_empty",
    "normalize_output",
    "replay",
    "tool_was_called",
    "truncate_observation",
    "validate_arguments",
]
